#!/usr/bin/python
# -*- coding: UTF-8 -*-    
# Author  : tuguoyi
# FileName: argparsertest.py
# DateTime: 3/9/21 4:56 PM

import argparse
import logging
import os
import sys
from pprint import pprint

def parse_arguments2():
    parser = argparse.ArgumentParser(description="the tool can be used to check whether two cpus are "
                                                 "compatible or not. you can typed '{} command -h' "
                                                 "for more detailed info".format(os.path.basename(sys.argv[0])))

    common_parser = argparse.ArgumentParser(add_help=False)
    common_parser.add_argument("--conf", type=str,
                               help="the file containing a list of cpu that has been compared. Each cpu entry "
                                    "contains the information of a specific cpu and the other cpus that it "
                                    "compatible or incompatible with")
    common_parser.add_argument("--base", type=str, required=True,
                               help="signature string of the base cpu with format "
                                    "family,model,stepping. e.g. 6,45,7 for SandyBridge")
    common_parser.add_argument("--target", type=str, required=True,
                               help="signature string of the target cpu with format "
                                      "family,model,stepping. e.g. 6,45,7 for SandyBridge")

    subparsers = parser.add_subparsers()
    subparsers.required = True
    subparsers.dest = "command"

    check_usage = "check if the target cpu is compatible with the base cpu by looking up the " \
                  "compatible or incompatible list from config file specified by --conf argument "
    check_subparser = subparsers.add_parser("check", help=check_usage, description=check_usage,
                                            parents=[common_parser])

    cmp_usage = "compare host CPU with a CPU described by an XML file. The xml file is usually " \
                "generated by executing 'virsh capabilities' on the base host. This command must " \
                "be executed on the target host, and the result will be updated to the config file " \
                "specified by --conf argument"
    cmp_subparser = subparsers.add_parser("compare", help=cmp_usage, description=cmp_usage,
                                          parents=[common_parser])
    cmp_subparser.add_argument("--cpu-desc", type=str, required=True,
                               help="file containing an XML CPU description")
    return parser.parse_args()


if __name__ == '__main__':
    logging.basicConfig(level=logging.INFO,
                        format='%(asctime)s[%(filename)s:%(lineno)s][%(levelname)s] %(message)s')

    args = parse_arguments2()
    pprint(args)



